export const contactList = [
  {
    id: 1,
    name: "Rezaul Karim",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: "Hey Man",
    lastTextTime: "12:58 PM",
  },
  {
    id: 2,
    name: "Jahed Mah",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: `I'm with @theindiandev`,
    lastTextTime: "12:45 PM",
  },
  {
    id: 3,
    name: "Rezaul Karim",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: "Hey Man",
    lastTextTime: "12:58 PM",
  },
  {
    id: 4,
    name: "Jahed Mah",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: `I'm with @theindiandev`,
    lastTextTime: "12:45 PM",
  },
  {
    id: 5,
    name: "Rezaul Karim",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: "Hey Man",
    lastTextTime: "12:58 PM",
  },
  {
    id: 6,
    name: "Jahed Mah",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: `I'm with @theindiandev`,
    lastTextTime: "12:45 PM",
  },
  {
    id: 7,
    name: "Rezaul Karim",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: "Hey Man",
    lastTextTime: "12:58 PM",
  },
  {
    id: 8,
    name: "Jahed Mah",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: `I'm with @theindiandev`,
    lastTextTime: "12:45 PM",
  },
  {
    id: 9,
    name: "Rezaul Karim",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: "Hey Man",
    lastTextTime: "12:58 PM",
  },
  {
    id: 10,
    name: "Jahed Mah",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: `I'm with @theindiandev`,
    lastTextTime: "12:45 PM",
  },
  {
    id: 11,
    name: "Rezaul Karim",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: "Hey Man",
    lastTextTime: "12:58 PM",
  },
  {
    id: 12,
    name: "Jahed Mah",
    profilePic: "https://images.news18.com/ibnlive/uploads/2020/08/1598341407_whatsapp-logo.jpg",
    lastText: `I'm with @theindiandev`,
    lastTextTime: "12:45 PM",
  },
];
export const messagesList = [
  {
    id: 1,
    messageType: "TEXT",
    text: "Hey Man 😁",
    senderID: 0,
    addedOn: "12:00 PM",
  },
  {
    id: 2,
    messageType: "TEXT",
    text: "Hey, What's up?",
    senderID: 1,
    addedOn: "12:01 PM",
  },
  {
    id: 3,
    messageType: "TEXT",
    text: "All Good, What about you?",
    senderID: 0,
    addedOn: "12:00 PM",
  },
  {
    id: 4,
    messageType: "TEXT",
    text: "I'm good as well",
    senderID: 1,
    addedOn: "12:00 PM",
  },
  {
    id: 5,
    messageType: "TEXT",
    text: "Great 😁",
    senderID: 0,
    addedOn: "12:00 PM",
  },
  {
    id: 5,
    messageType: "TEXT",
    text: "Have you subscribed The Indian Dev ?",
    senderID: 1,
    addedOn: "12:00 PM",
  },
];
