export const ADMISSION_FIRST_STEP = 'ADMISSION_FIRST_STEP';
export const ADMISSION_SECOND_STEP = 'ADMISSION_SECOND_STEP';
export const ADMISSION_FINAL_STEP = 'ADMISSION_FINAL_STEP';
export const LOADING = 'LOADING';
export const LOADED = 'LOADED';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const FILE_UPLOAD = 'FILE_UPLOAD';
export const FILE_FAIL = 'FILE_FAIL';
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
export const LOGIN_ACCOUNT_FAILED = 'LOGIN_ACCOUNT_FAILED';
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const ALL_USERS = 'ALL_USERS';
export const CURRENT_USER = 'CURRENT_USER';
export const CONNECT = 'CONNECT';
export const DISCONNECT = 'DISCONNECT';
export const ACCEPT_CONNECTION_REQUEST = 'ACCEPT_CONNECTION_REQUEST';
export const SEARCHING = 'SEARCHING';
export const FOLLOWERS = 'FOLLOWERS';
export const FOLLOWINGS = 'FOLLOWINGS';
export const UPDATE_INFO = 'UPDATE_INFO';
export const POSTS = 'POSTS';
export const NEW_POST = 'NEW_POST';
export const DELETE_POST = 'DELETE_POST';
export const SUGGESTIONS = 'SUGGESTIONS';
export const COMMENT = 'COMMENT';
export const DELETE_EDUCATION_BACKGROUND = 'DELETE_EDUCATION_BACKGROUND';
export const DELETE_JOB = 'DELETE_JOB';
export const LIKE_AND_DISLIKE = 'LIKE_AND_DISLIKE';
export const POST_NOTIFICATIONS = 'POST_NOTIFICATIONS';
export const SHOW_POST_NOTIFICATIONS = 'SHOW_POST_NOTIFICATIONS';
export const CREATE_CLUB = 'CREATE_CLUB';
export const CREATE_GROUP = 'CREATE_GROUP';
export const ALL_CLUB = 'ALL_CLUB';
export const ALL_GROUP = 'ALL_GROUP';

export const CLUB_UPDATE = 'CLUB_UPDATE';
export const CLUB_UNFOLLOW = 'CLUB_UNFOLLOW';
export const CLUB_FOLLOW = 'CLUB_FOLLOW';
export const CLUB_POST = 'CLUB_POST';

export const GROUP_UPDATE = 'GROUP_UPDATE';
export const MEMBER_REQUEST = 'MEMBER_REQUEST';
export const CANCEL_REQUEST = 'CANCEL_REQUEST';
export const REJECT_REQUEST = 'REJECT_REQUEST';
export const ACCEPT_REQUEST = 'ACCEPT_REQUEST';
export const GROUP_POST = 'GROUP_POST';

export const PEER = 'PEER';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const MESSAGES = 'MESSAGES';
export const REAL_TIME_MESSAGE = 'REAL_TIME_MESSAGE';

export const ADD_DEPARTMENT = 'ADD_DEPARTMENT';
export const ALL_DEPARTMENT = 'ALL_DEPARTMENT';
export const ADD_COURSE = 'ADD_COURSE';
export const ALL_COURSE = 'ALL_COURSE';
export const ADD_TEACHER = 'ADD_TEACHER';
export const ALL_TEACHER = 'ALL_TEACHER';
export const ADD_STUDENT = 'ADD_STUDENT';
export const ALL_STUDENT = 'ALL_STUDENT';
export const SEMESTER_REGISTRATION = 'SEMESTER_REGISTRATION';
export const ALL_SEMESTERS = 'ALL_SEMESTERS';


